[package]
name = "aurora"
version = "0.1.0"
description = "A local-first cinematic music player."
authors = ["Aurora"]
edition = "2021"

[lib]
name = "aurora_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
